services:
  app:
    build: .
    container_name: car-directory-manager-app
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_APPLICATION_NAME=CarDirectoryManager
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/CarDirectoryDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration
      - SPRING_CARDIRECTORYMANAGER_JWTSECRET=k3lM3J1Q4oP7hT9sZ2xV6bN8cF5dG1jK3mO5qR7tU9wX2zB4vC6yH8nJ0pL2sD4f
      - SPRING_CARDIRECTORYMANAGER_JWTEXPIRATIONMS=86400000
    networks:
      - app-network

  db:
    image: postgres
    container_name: car-directory-manager-db
    environment:
      - POSTGRES_DB=CarDirectoryDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5438:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin4_containerr
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5058:81"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

volumes:
  db_data:
  pgadmin-data:

networks:
  app-network:
